const cities = [
    { infection:false, name:'Hollow Men Gather', color:'gray'   },
    { infection:false, name:'Hollow Men Gather', color:'gray'   },
    { infection:false, name:'Hollow Men Gather', color:'gray'   },
    { infection:false, name:'Hollow Men Gather', color:'gray'   },
    { infection:true , name:'Buenos Aires',      color:'yellow' },
    { infection:true , name:'Buenos Aires',      color:'yellow' },
    { infection:true , name:'Cairo',             color:'black'  },
    { infection:true , name:'Cairo',             color:'black'  },
    { infection:true , name:'Cairo',             color:'black'  },
    { infection:true , name:'Chicago',           color:'blue'   },
    { infection:true , name:'Chicago',           color:'blue'   },
    { infection:true , name:'Denver',            color:'blue'   },
    { infection:true , name:'Denver',            color:'blue'   },
    { infection:true , name:'Frankfurt',         color:'blue'   },
    { infection:true , name:'Frankfurt',         color:'blue'   },
    { infection:true , name:'Istanbul',          color:'black'  },
    { infection:true , name:'Jacksonville',      color:'yellow' },
    { infection:true , name:'Jacksonville',      color:'yellow' },
    { infection:true , name:'Jacksonville',      color:'yellow' },
    { infection:true , name:'Lagos',             color:'yellow' },
    { infection:true , name:'Lagos',             color:'yellow' },
    { infection:true , name:'Lagos',             color:'yellow' },
    { infection:true , name:'Lima',              color:'yellow' },
    { infection:true , name:'London',            color:'blue'   },
    { infection:true , name:'London',            color:'blue'   },
    { infection:true , name:'London',            color:'blue'  , modifier:'Well Stocked' },
    { infection:true , name:'Los Angeles',       color:'yellow' },
    { infection:true , name:'Mexico City',       color:'yellow', modifier:'Well Stocked' },
    { infection:true , name:'Moscow',            color:'black'  },
    { infection:true , name:'New York',          color:'blue'   },
    { infection:true , name:'New York',          color:'blue'   },
    { infection:true , name:'New York',          color:'blue'   },
    { infection:true , name:'Paris',             color:'blue'   },
    { infection:true , name:'San Francisco',     color:'blue'   },
    { infection:true , name:'San Francisco',     color:'blue'   },
    { infection:true , name:'Santiago',          color:'yellow' },
    { infection:true , name:'S&atilde;o Paulo',  color:'yellow' },
    { infection:true , name:'S&atilde;o Paulo',  color:'yellow' },
    { infection:true , name:'St. Petersburg',    color:'blue'   },
    { infection:true , name:'Tripoli',           color:'black'  },
    { infection:true , name:'Tripoli',           color:'black'  },
    { infection:true , name:'Tripoli',           color:'black'  },
    { infection:true , name:'Washington',        color:'blue'   },
    { infection:true , name:'Washington',        color:'blue'   },
    { infection:true , name:'Washington',        color:'blue'   },
];
