const cities = [
    { name:'Atlanta',          color:'blue'   },
    { name:'Cairo',            color:'black'  },
    { name:'Cairo',            color:'black'  },
    { name:'Cairo',            color:'black'  },
    { name:'Chicago',          color:'blue'   },
    { name:'Chicago',          color:'blue'   },
    { name:'Denver',           color:'blue'   },
    { name:'Denver',           color:'blue'   },
    { name:'Istanbul',         color:'black'  },
    { name:'Istanbul',         color:'black'  },
    { name:'Istanbul',         color:'black'  },
    { name:'Jacksonville',     color:'yellow' },
    { name:'Jacksonville',     color:'yellow' },
    { name:'Jacksonville',     color:'yellow' },
    { name:'Lagos',            color:'yellow' },
    { name:'Lagos',            color:'yellow' },
    { name:'Lagos',            color:'yellow' },
    { name:'London',           color:'blue'   },
    { name:'London',           color:'blue'   },
    { name:'London',           color:'blue'  , modifier: 'Well Stocked' },
    { name:'Los Angeles',      color:'yellow' },
    { name:'Mexico City',      color:'yellow', modifier: 'Well Stocked' },
    { name:'New York',         color:'blue'   },
    { name:'New York',         color:'blue'   },
    { name:'New York',         color:'blue'   },
    { name:'Paris',            color:'blue'   },
    { name:'Paris',            color:'blue'   },
    { name:'San Francisco',    color:'blue'   },
    { name:'San Francisco',    color:'blue'   },
    { name:'S&atilde;o Paulo', color:'yellow' },
    { name:'S&atilde;o Paulo', color:'yellow' },
    { name:'S&atilde;o Paulo', color:'yellow' },
    { name:'Tripoli',          color:'black'  },
    { name:'Tripoli',          color:'black'  },
    { name:'Tripoli',          color:'black'  },
    { name:'Washington',       color:'blue'   },
    { name:'Washington',       color:'blue'   },
    { name:'Washington',       color:'blue'   },
];
