const defaultCityCards = 55;
const defaultFunding   =  0;
const defaultResources = 12;

const cities = [
    { name:'Buenos Aires',     color:'yellow' },
    { name:'Buenos Aires',     color:'yellow' },
    { name:'Cairo',            color:'black'  },
    { name:'Cairo',            color:'black'  },
    { name:'Cairo',            color:'black'  },
    { name:'Chicago',          color:'blue'   },
    { name:'Chicago',          color:'blue'   },
    { name:'Denver',           color:'blue'   },
    { name:'Denver',           color:'blue'   },
    { name:'Frankfurt',        color:'blue'   },
    { name:'Frankfurt',        color:'blue'   },
    { name:'Istanbul',         color:'black'  },
    { name:'Jacksonville',     color:'yellow' },
    { name:'Jacksonville',     color:'yellow' },
    { name:'Jacksonville',     color:'yellow' },
    { name:'Lagos',            color:'yellow' },
    { name:'Lagos',            color:'yellow' },
    { name:'Lagos',            color:'yellow' },
    { name:'Lima',             color:'yellow' },
    { name:'London',           color:'blue'   },
    { name:'London',           color:'blue'   },
    { name:'London',           color:'blue'  , modifier: 'Well Stocked' },
    { name:'Los Angeles',      color:'yellow' },
    { name:'Mexico City',      color:'yellow', modifier: 'Well Stocked' },
    { name:'Moscow',           color:'black'  },
    { name:'New York',         color:'blue'   },
    { name:'New York',         color:'blue'   },
    { name:'New York',         color:'blue'   },
    { name:'Paris',            color:'blue'   },
    { name:'San Francisco',    color:'blue'   },
    { name:'San Francisco',    color:'blue'   },
    { name:'Santiago',         color:'yellow' },
    { name:'S&atilde;o Paulo', color:'yellow' },
    { name:'S&atilde;o Paulo', color:'yellow' },
    { name:'St. Petersburg',   color:'blue'   },
    { name:'Tripoli',          color:'black'  },
    { name:'Tripoli',          color:'black'  },
    { name:'Tripoli',          color:'black'  },
    { name:'Washington',       color:'blue'   },
    { name:'Washington',       color:'blue'   },
    { name:'Washington',       color:'blue'   },
];
