import { Chapter } from "./chapter";
import { ChapterDecks } from "./chapter-decks";

export const Chapters: ChapterDecks = {
    'a': [
        new Chapter('a', false, ['j', 's'], "The Wrong Place At The Wrong Time"),
        new Chapter('a', false, ['j', 'h'], "A Race To The Treasure"),
        new Chapter('a', false, ['j', 'r'], "The Epic Duel"),
        new Chapter('a', false, ['s', 'h'], "The Bad Part Of Town"),
        new Chapter('a', false, ['s', 'r'], "Mid-Life Crisis"),
        new Chapter('a', false, ['j', 's'], "Laugh In The Face Of Death"),
        new Chapter('a', true , ['j', 'a'], "Blackout"),
        new Chapter('a', false, ['h', 'a'], "I Don't Believe In Monsters"),
        new Chapter('a', false, ['s', 'a'], "Let's Blow This Thing Up"),
        new Chapter('a', false, ['h', 'r'], "Follow The Clues"),
        new Chapter('a', false, ['j', 'h'], "A Perilous Journey"),
        new Chapter('a', false, ['r', 'a'], "A Scream In The Night"),
        new Chapter('a', false, ['j', 's'], "Sink Or Swim"),
        new Chapter('a', false, ['j', 'r'], "Hidden Talents"),
        new Chapter('a', false, ['s', 'h'], "Natural Disaster"),
        new Chapter('a', false, ['j', 'h'], "That Looks Radioactive"),
        new Chapter('a', false, ['s', 'r'], "Training Montage"),
        new Chapter('a', false, ['j', 's'], "Run For Your Life!"),
        new Chapter('a', false, ['j', 'a'], "A Brute Force Solution"),
        new Chapter('a', false, ['h', 'r'], "I'm The Best Chance You Have"),
        new Chapter('a', false, ['j', 'h'], "The Hunter Is Hunted"),
        new Chapter('a', false, ['h', 'a'], "A Series Of Deadly Traps"),
        new Chapter('a', false, ['s', 'a'], "It's Quiet, Too Quiet"),
        new Chapter('a', false, ['r', 'a'], "Sudden Reinforcements"),
        new Chapter('a', false, ['j', 's'], "Sabotage"),
        new Chapter('a', false, ['s', 'h'], "Is It Real Or A Hallucination?"),
        new Chapter('a', false, ['s', 'r'], "You Made It Worse"),
        new Chapter('a', false, ['j', 'r'], "Fight To The Death"),
        new Chapter('a', false, ['j', 'h'], "How Far Down Does This Go?"),
        new Chapter('a', false, ['j', 's'], "That Looks Painful"),
    ],
    'h': [
        new Chapter('h', false, ['r', 'a'], "Madness Or Genius?"),
        new Chapter('h', false, ['r', 'j'], "Amnesia"),
        new Chapter('h', false, ['a', 'j'], "Secret Tunnels"),
        new Chapter('h', false, ['a', 's'], "A Rare Disease"),
        new Chapter('h', false, ['r', 's'], "Addiction"),
        new Chapter('h', false, ['r', 'a'], "Not Entirely Human"),
        new Chapter('h', true , ['r', 'h'], "Abracadabra"),
        new Chapter('h', false, ['j', 'h'], "If I'm A Clone, Where's The Original?"),
        new Chapter('h', false, ['s', 'h'], "Unique Genetics"),
        new Chapter('h', false, ['r', 'j'], "I'm More Than Just A Pretty Face"),
        new Chapter('h', false, ['a', 'h'], "The Chosen One"),
        new Chapter('h', false, ['j', 's'], "You Need To See The Big Picture"),
        new Chapter('h', false, ['r', 'a'], "'X' Marks The Spot"),
        new Chapter('h', false, ['a', 'j'], "A Premonition"),
        new Chapter('h', false, ['r', 's'], "Descended From Royalty"),
        new Chapter('h', false, ['a', 's'], "Rewriting History"),
        new Chapter('h', false, ['r', 'j'], "A Secret Uncovered"),
        new Chapter('h', false, ['r', 'a'], "I've Never Seen Anything Like This Before"),
        new Chapter('h', false, ['j', 'h'], "What's Under The House?"),
        new Chapter('h', false, ['a', 'h'], "An Ancient Artefact"),
        new Chapter('h', false, ['s', 'h'], "It Is Tradition"),
        new Chapter('h', false, ['r', 'h'], "I've Had It Since Birth"),
        new Chapter('h', false, ['j', 's'], "They'll Never Let Me Forget"),
        new Chapter('h', false, ['r', 'j'], "Beg For Forgiveness"),
        new Chapter('h', false, ['r', 'a'], "I Knew There Was Something I Forgot To Do"),
        new Chapter('h', false, ['r', 's'], "Adopted"),
        new Chapter('h', false, ['a', 'j'], "In Your Ancestor's Shadow"),
        new Chapter('h', false, ['a', 's'], "I'm Never Going Back To Prison"),
        new Chapter('h', false, ['r', 'j'], "I Can Read Your Mind"),
        new Chapter('h', false, ['r', 'a'], "That Brings Back Memories"),
    ],
    'j': [
        new Chapter('j', false, ['s', 'h'], "There's Worse Things Than Death"),
        new Chapter('j', false, ['s', 'r'], "No One Will Believe You"),
        new Chapter('j', false, ['s', 'a'], "It's A Matter Of Life And Death"),
        new Chapter('j', false, ['h', 'r'], "They Never Found the Body"),
        new Chapter('j', false, ['h', 'a'], "I Know His Weakness"),
        new Chapter('j', false, ['s', 'h'], "That's The Evidence We Need"),
        new Chapter('j', true , ['s', 'j'], "A Last Minute Reprieve"),
        new Chapter('j', false, ['r', 'j'], "It's Not What It Looks Like"),
        new Chapter('j', false, ['r', 'a'], "Choose Who To Save"),
        new Chapter('j', false, ['a', 'j'], "No Security Can Keep Me Out"),
        new Chapter('j', false, ['s', 'r'], "I Hope You have An Alibi"),
        new Chapter('j', false, ['h', 'j'], "Get A Good Lawyer"),
        new Chapter('j', false, ['s', 'h'], "Why Are The Police Here?"),
        new Chapter('j', false, ['s', 'a'], "Here's The Plan"),
        new Chapter('j', false, ['s', 'r'], "Make A Wish"),
        new Chapter('j', false, ['h', 'r'], "Did You See Him Die?"),
        new Chapter('j', false, ['h', 'a'], "Capital Punishment"),
        new Chapter('j', false, ['s', 'h'], "Saved By Something Worse"),
        new Chapter('j', false, ['r', 'a'], "Prison Break"),
        new Chapter('j', false, ['s', 'j'], "The Black Market"),
        new Chapter('j', false, ['h', 'j'], "You Can't Say That Here"),
        new Chapter('j', false, ['s', 'r'], "I Hate That You're Right"),
        new Chapter('j', false, ['r', 'j'], "Kidnapped!"),
        new Chapter('j', false, ['a', 'j'], "A Guardian Angel"),
        new Chapter('j', false, ['s', 'h'], "Be Careful What You Wish For"),
        new Chapter('j', false, ['s', 'a'], "You'll Regret That"),
        new Chapter('j', false, ['h', 'a'], "An Eye For An Eye"),
        new Chapter('j', false, ['h', 'r'], "Replaced By An Imposter"),
        new Chapter('j', false, ['s', 'r'], "Stockholm Syndrome"),
        new Chapter('j', false, ['s', 'h'], "You'll Get What You Deserve"),
    ],
    'r': [
        new Chapter('r', false, ['a', 'j'], "Ransom"),
        new Chapter('r', false, ['a', 's'], "Forbidden Love"),
        new Chapter('r', false, ['a', 'h'], "The Absent-Minded Inventor"),
        new Chapter('r', false, ['j', 'h'], "Separated At Birth"),
        new Chapter('r', false, ['j', 's'], "Betrayed By My Best Friend"),
        new Chapter('r', false, ['a', 'j'], "I Can't Live Without You"),
        new Chapter('r', true , ['a', 'r'], "Love At First Sight"),
        new Chapter('r', false, ['s', 'r'], "You Love That Machine More Than You Love Me"),
        new Chapter('r', false, ['h', 'r'], "Reunion"),
        new Chapter('r', false, ['a', 's'], "A Mysterious Foreigner"),
        new Chapter('r', false, ['j', 'r'], "Found Love Too Late"),
        new Chapter('r', false, ['s', 'h'], "The Generation Gap"),
        new Chapter('r', false, ['a', 'j'], "They Died In My Arms"),
        new Chapter('r', false, ['a', 's'], "A Long Distance Relationship"),
        new Chapter('r', false, ['a', 'h'], "Blood Pact"),
        new Chapter('r', false, ['j', 's'], "A Dangerous Affair"),
        new Chapter('r', false, ['j', 'h'], "Left At The Alter"),
        new Chapter('r', false, ['a', 'j'], "A Worthy Opponent"),
        new Chapter('r', false, ['h', 'r'], "Evil Twin"),
        new Chapter('r', false, ['s', 'r'], "Dysfunctional Family"),
        new Chapter('r', false, ['a', 's'], "'Til Death Do We Part"),
        new Chapter('r', false, ['j', 'r'], "It Followed Me Home"),
        new Chapter('r', false, ['s', 'h'], "How I Met My Father"),
        new Chapter('r', false, ['a', 'r'], "A Gift From A Secret Admirer"),
        new Chapter('r', false, ['a', 'j'], "Shotgun Wedding"),
        new Chapter('r', false, ['j', 's'], "Keeping Bad Company"),
        new Chapter('r', false, ['j', 'h'], "Master And Apprentice"),
        new Chapter('r', false, ['a', 'h'], "A Night To Remember"),
        new Chapter('r', false, ['a', 's'], "The Ex-"),
        new Chapter('r', false, ['a', 'j'], "Lose A Child"),
    ],
    's': [
        new Chapter('s', false, ['h', 'r'], "There's More Important Things Than Money"),
        new Chapter('s', false, ['h', 'a'], "The Luxury Yacht"),
        new Chapter('s', false, ['r', 'j'], "Join The Dark Side"),
        new Chapter('s', false, ['h', 'j'], "Brainwashing"),
        new Chapter('s', false, ['r', 'a'], "Week-Long Festival"),
        new Chapter('s', false, ['h', 'r'], "Slaves To The Elite"),
        new Chapter('s', true , ['h', 's'], "This Is Not Reality"),
        new Chapter('s', false, ['j', 's'], "An Untested Drug"),
        new Chapter('s', false, ['a', 'j'], "Surrender Or Die"),
        new Chapter('s', false, ['h', 'a'], "Men In Black"),
        new Chapter('s', false, ['a', 's'], "Nothing Is Private"),
        new Chapter('s', false, ['r', 's'], "We Are As Gods"),
        new Chapter('s', false, ['h', 'r'], "I Don't Belong Here"),
        new Chapter('s', false, ['r', 'j'], "I Should Be The Leader"),
        new Chapter('s', false, ['h', 'j'], "That Wasn't A Simulation"),
        new Chapter('s', false, ['r', 'a'], "Hated By Everyone"),
        new Chapter('s', false, ['h', 'a'], "The Royal Gala Event"),
        new Chapter('s', false, ['h', 'r'], "A Cure For Cancer"),
        new Chapter('s', false, ['h', 's'], "A Sinister Conspiracy"),
        new Chapter('s', false, ['j', 's'], "We Can, But Should We?"),
        new Chapter('s', false, ['a', 'j'], "You're Fired!"),
        new Chapter('s', false, ['r', 's'], "Who Has This Kind Of Technology?"),
        new Chapter('s', false, ['h', 'a'], "The Hidden World Within Our Own"),
        new Chapter('s', false, ['a', 's'], "Glory To The Leader"),
        new Chapter('s', false, ['h', 'r'], "Your Money's No Good Here"),
        new Chapter('s', false, ['r', 'j'], "From Rags To Riches"),
        new Chapter('s', false, ['r', 'a'], "A Sacrifice To The Gods"),
        new Chapter('s', false, ['h', 'j'], "That's Not Chicken You're Eating"),
        new Chapter('s', false, ['h', 'a'], "Terrorism"),
        new Chapter('s', false, ['h', 'r'], "Trespassing On Native Land"),
    ],
};
