const defaultCards = [
    { deck:'Infection'  , infection:false, name:'Hollow Men Gather', color:'gray'   },
    { deck:'Infection'  , infection:false, name:'Hollow Men Gather', color:'gray'   },
    { deck:'Infection'  , infection:false, name:'Hollow Men Gather', color:'gray'   },
    { deck:'Infection'  , infection:false, name:'Hollow Men Gather', color:'gray'   },
    { deck:'Innoculated', infection:true , name:'Atlanta',           color:'blue'   },
    { deck:'Infection'  , infection:true , name:'Baghdad',           color:'black'  },
    { deck:'Infection'  , infection:true , name:'Baghdad',           color:'black'  },
    { deck:'Reserve'    , infection:true , name:'Bogotá',            color:'yellow' },
    { deck:'Reserve'    , infection:true , name:'Bogotá',            color:'yellow' },
    { deck:'Infection'  , infection:true , name:'Buenos Aires',      color:'yellow' },
    { deck:'Infection'  , infection:true , name:'Buenos Aires',      color:'yellow' },
    { deck:'Infection'  , infection:true , name:'Cairo',             color:'black'  },
    { deck:'Infection'  , infection:true , name:'Cairo',             color:'black'  },
    { deck:'Innoculated', infection:true , name:'Cairo',             color:'black'  },
    { deck:'Infection'  , infection:true , name:'Chicago',           color:'blue'   },
    { deck:'Infection'  , infection:true , name:'Chicago',           color:'blue'   },
    { deck:'Reserve'    , infection:true , name:'Delhi',             color:'black'  },
    { deck:'Infection'  , infection:true , name:'Denver',            color:'blue'   },
    { deck:'Infection'  , infection:true , name:'Denver',            color:'blue'   },
    { deck:'Infection'  , infection:true , name:'Frankfurt',         color:'blue'   },
    { deck:'Infection'  , infection:true , name:'Frankfurt',         color:'blue'   },
    { deck:'Infection'  , infection:true , name:'Istanbul',          color:'black'  },
    { deck:'Destroyed'  , infection:true , name:'Istanbul',          color:'black'  },
    { deck:'Destroyed'  , infection:true , name:'Istanbul',          color:'black'  },
    { deck:'Infection'  , infection:true , name:'Jacksonville',      color:'yellow' },
    { deck:'Infection'  , infection:true , name:'Jacksonville',      color:'yellow' },
    { deck:'Innoculated', infection:true , name:'Jacksonville',      color:'yellow' },
    { deck:'Reserve'    , infection:true , name:'Kolkata',           color:'black'  },
    { deck:'Infection'  , infection:true , name:'Lagos',             color:'yellow' },
    { deck:'Infection'  , infection:true , name:'Lagos',             color:'yellow' },
    { deck:'Innoculated', infection:true , name:'Lagos',             color:'yellow' },
    { deck:'Infection'  , infection:true , name:'Lima',              color:'yellow' },
    { deck:'Infection'  , infection:true , name:'London',            color:'blue'  , upgrade:'Well Stocked' },
    { deck:'Innoculated', infection:true , name:'London',            color:'blue'   },
    { deck:'Innoculated', infection:true , name:'London',            color:'blue'   },
    { deck:'Infection'  , infection:true , name:'Los Angeles',       color:'yellow' },
    { deck:'Infection'  , infection:true , name:'Mexico City',       color:'yellow', upgrade:'Well Stocked' },
    { deck:'Infection'  , infection:true , name:'Moscow',            color:'black'  },
    { deck:'Reserve'    , infection:true , name:'New Mumbai',        color:'black'  },
    { deck:'Reserve'    , infection:true , name:'New Mumbai',        color:'black'  },
    { deck:'Infection'  , infection:true , name:'New York',          color:'blue'   },
    { deck:'Infection'  , infection:true , name:'New York',          color:'blue'   },
    { deck:'Innoculated', infection:true , name:'New York',          color:'blue'   },
    { deck:'Infection'  , infection:true , name:'Paris',             color:'blue'   },
    { deck:'Innoculated', infection:true , name:'Paris',             color:'blue'   },
    { deck:'Reserve'    , infection:true , name:'Riyadh',            color:'black'  },
    { deck:'Reserve'    , infection:true , name:'Riyadh',            color:'black'  },
    { deck:'Infection'  , infection:true , name:'San Francisco',     color:'blue'   },
    { deck:'Innoculated', infection:true , name:'San Francisco',     color:'blue'   },
    { deck:'Infection'  , infection:true , name:'Santiago',          color:'yellow' },
    { deck:'Infection'  , infection:true , name:'São Paulo',         color:'yellow' },
    { deck:'Infection'  , infection:true , name:'São Paulo',         color:'yellow' },
    { deck:'Innoculated', infection:true , name:'São Paulo',         color:'yellow' },
    { deck:'Infection'  , infection:true , name:'St. Petersburg',    color:'blue'   },
    { deck:'Reserve'    , infection:true , name:'Tehran',            color:'black'  },
    { deck:'Infection'  , infection:true , name:'Tripoli',           color:'black'  },
    { deck:'Innoculated', infection:true , name:'Tripoli',           color:'black'  },
    { deck:'Innoculated', infection:true , name:'Tripoli',           color:'black'  },
    { deck:'Infection'  , infection:true , name:'Washington',        color:'blue'   },
    { deck:'Infection'  , infection:true , name:'Washington',        color:'blue'   },
    { deck:'Infection'  , infection:true , name:'Washington',        color:'blue'   },
];
