const defaultCityCards = 48;
const defaultEpidemicCards = 5;
const defaultFundingCards = 5;
const defaultResourceCards = 0;
const defaultCards = [
    { deck:'Threat', name:'Algiers'      , affiliation:'Allied' , region:'Africa'       , incident:'Sleeper Cells Activate: North America' },
    { deck:'Threat', name:'Atlanta'      , affiliation:'Allied' , region:'North America', incident:'Sleeper Cells Activate: Asia' },
    { deck:'Threat', name:'Baghdad'      , affiliation:'Soviet' , region:'Asia'         , incident:'Sleeper Cells Activate: Pacific Rim' },
    { deck:'Threat', name:'Bangkok'      , affiliation:'Neutral', region:'Asia'         , incident:'Teams Compromised' },
    { deck:'Threat', name:'Bogotá'       , affiliation:'Neutral', region:'South America', incident:'Sleeper Cells Activate: North America' },
    { deck:'Threat', name:'Bombay'       , affiliation:'Neutral', region:'Asia'         , incident:'Sleeper Cells Activate: Pacific Rim' },
    { deck:'Threat', name:'Buenos Aires' , affiliation:'Neutral', region:'South America', incident:'Recognized: South America, Europe' },
    { deck:'Threat', name:'Cairo'        , affiliation:'Soviet' , region:'Africa'       , incident:'Sleeper Cells Activate: Europe' },
    { deck:'Threat', name:'Calcutta'     , affiliation:'Neutral', region:'Asia'         , incident:'Sleeper Cells Activate: Africa' },
    { deck:'Threat', name:'Delhi'        , affiliation:'Neutral', region:'Asia'         , incident:'Sleeper Cells Activate: Africa' },
    { deck:'Threat', name:'East Berlin'  , affiliation:'Soviet' , region:'Europe'       , incident:'Sleeper Cells Activate: South America' },
    { deck:'Threat', name:'Hanoi'        , affiliation:'Soviet' , region:'Asia'         , incident:'Sleeper Cells Activate: South America' },
    { deck:'Threat', name:'Havana'       , affiliation:'Soviet' , region:'North America', incident:'Safehouse Compromised: Asia' },
    { deck:'Threat', name:'Istanbul'     , affiliation:'Allied' , region:'Europe'       , incident:'Safehouse Compromised: Africa' },
    { deck:'Threat', name:'Jakarta'      , affiliation:'Neutral', region:'Pacific Rim'  , incident:'Sleeper Cells Activate: Europe' },
    { deck:'Threat', name:'Johannesburg' , affiliation:'Allied' , region:'Africa'       , incident:'Safehouse Compromised: South America' },
    { deck:'Threat', name:'Karachi'      , affiliation:'Neutral', region:'Asia'         , incident:'Sleeper Cells Activate: South America' },
    { deck:'Threat', name:'Khartoum'     , affiliation:'Neutral', region:'Africa'       , incident:'Sleeper Cells Activate: Asia' },
    { deck:'Threat', name:'Kiev'         , affiliation:'Neutral', region:'Europe'       , incident:'Safehouse Compromised: Pacific Rim' },
    { deck:'Threat', name:'Lagos'        , affiliation:'Neutral', region:'Africa'       , incident:'Sleeper Cells Activate: South America' },
    { deck:'Threat', name:'Leningrad'    , affiliation:'Soviet' , region:'Europe'       , incident:'Teams Compromised' },
    { deck:'Threat', name:'Leopoldville' , affiliation:'Neutral', region:'Africa'       , incident:'Recognized: Africa, Asia' },
    { deck:'Threat', name:'Lima'         , affiliation:'Neutral', region:'South America', incident:'Sleeper Cells Activate: Europe' },
    { deck:'Threat', name:'London'       , affiliation:'Allied' , region:'Europe'       , incident:'Sleeper Cells Activate: Asia' },
    { deck:'Threat', name:'Los Angeles'  , affiliation:'Allied' , region:'North America', incident:'Sleeper Cells Activate: Europe' },
    { deck:'Threat', name:'Madrid'       , affiliation:'Neutral', region:'Europe'       , incident:'Sleeper Cells Activate: Pacific Rim' },
    { deck:'Threat', name:'Manila'       , affiliation:'Neutral', region:'Pacific Rim'  , incident:'Sleeper Cells Activate: Asia' },
    { deck:'Threat', name:'Mexico City'  , affiliation:'Neutral', region:'North America', incident:'Sleeper Cells Activate: Pacific Rim' },
    { deck:'Threat', name:'Moscow'       , affiliation:'Soviet' , region:'Europe'       , incident:'Recognized: Europe, Asia' },
    { deck:'Threat', name:'New York'     , affiliation:'Allied' , region:'North America', incident:'Recognized: North America, South America' },
    { deck:'Threat', name:'Novosibirisk' , affiliation:'Soviet' , region:'Asia'         , incident:'Sleeper Cells Activate: Europe' },
    { deck:'Threat', name:'Osaka'        , affiliation:'Neutral', region:'Pacific Rim'  , incident:'Recognized: Pacific Rim, North America' },
    { deck:'Threat', name:'Paris'        , affiliation:'Allied' , region:'Europe'       , incident:'Sleeper Cells Activate: North America' },
    { deck:'Threat', name:'Peking'       , affiliation:'Soviet' , region:'Asia'         , incident:'Safehouse Compromised: North America' },
    { deck:'Threat', name:'Prague'       , affiliation:'Soviet' , region:'Europe'       , incident:'Sleeper Cells Activate: Asia' },
    { deck:'Threat', name:'Pyongyang'    , affiliation:'Soviet' , region:'Asia'         , incident:'Safehouse Compromised: Europe' },
    { deck:'Threat', name:'Riyadh'       , affiliation:'Neutral', region:'Asia'         , incident:'Sleeper Cells Activate: North America' },
    { deck:'Threat', name:'Rome'         , affiliation:'Allied' , region:'Europe'       , incident:'Sleeper Cells Activate: Africa' },
    { deck:'Threat', name:'Saigon'       , affiliation:'Allied' , region:'Asia'         , incident:'Recognized: Asia, Pacific Rim' },
    { deck:'Threat', name:'San Francisco', affiliation:'Allied' , region:'North America', incident:'Sleeper Cells Activate: South America' },
    { deck:'Threat', name:'Santiago'     , affiliation:'Neutral', region:'South America', incident:'Sleeper Cells Activate: Africa' },
    { deck:'Threat', name:'São Paulo'    , affiliation:'Neutral', region:'South America', incident:'Teams Compromised' },
    { deck:'Threat', name:'Shanghai'     , affiliation:'Soviet' , region:'Asia'         , incident:'Teams Compromised' },
    { deck:'Threat', name:'Sydney'       , affiliation:'Allied' , region:'Pacific Rim'  , incident:'Teams Compromised' },
    { deck:'Threat', name:'Tokyo'        , affiliation:'Neutral', region:'Pacific Rim'  , incident:'Sleeper Cells Activate: North America' },
    { deck:'Threat', name:'Toronto'      , affiliation:'Allied' , region:'North America', incident:'Sleeper Cells Activate: Africa' },
    { deck:'Threat', name:'Warsaw'       , affiliation:'Soviet' , region:'Europe'       , incident:'Sleeper Cells Activate: Pacific Rim' },
    { deck:'Threat', name:'Washington'   , affiliation:'Allied' , region:'North America', incident:'Teams Compromised' },
];
