#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TableTennis.Droid.Resource", IsApplication=true)]

namespace TableTennis.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int games_options = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int goal_options = 2131165185;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int team1 = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int team1_win = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int team2 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int team2_win = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int grid_line_width = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090003
			public const int CopyrightText = 2131296259;
			
			// aapt resource value: 0x7f090014
			public const int Games = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int Goal = 2131296277;
			
			// aapt resource value: 0x7f090016
			public const int PlayButton = 2131296278;
			
			// aapt resource value: 0x7f090004
			public const int StartButton = 2131296260;
			
			// aapt resource value: 0x7f09000c
			public const int Team1Name = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int Team1Player1Name = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int Team1Player2Name = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int Team1Player3Name = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int Team2Name = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int Team2Player1Name = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int Team2Player2Name = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int Team2Player3Name = 2131296275;
			
			// aapt resource value: 0x7f090002
			public const int TitleText = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int gameFragment_player1Score = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int gameFragment_player2Score = 2131296257;
			
			// aapt resource value: 0x7f090006
			public const int matchFragment_gamesLayout = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int matchFragment_player1Name = 2131296261;
			
			// aapt resource value: 0x7f090007
			public const int matchFragment_player2Name = 2131296263;
			
			// aapt resource value: 0x7f09000a
			public const int scoreboard_matchesLayout = 2131296266;
			
			// aapt resource value: 0x7f090008
			public const int scoreboard_rootLayout = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int scoreboard_team1Name = 2131296265;
			
			// aapt resource value: 0x7f09000b
			public const int scoreboard_team2Name = 2131296267;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int GameFragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MatchFragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Scoreboard = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TeamInput = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int copyright = 2131099653;
			
			// aapt resource value: 0x7f06000f
			public const int default_games_option = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int default_goal_option = 2131099664;
			
			// aapt resource value: 0x7f06000c
			public const int games_prompt = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int goal_prompt = 2131099661;
			
			// aapt resource value: 0x7f060001
			public const int main_activity = 2131099649;
			
			// aapt resource value: 0x7f06000e
			public const int play_button = 2131099662;
			
			// aapt resource value: 0x7f060009
			public const int player_1_name_placeholder = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int player_2_name_placeholder = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int player_3_name_placeholder = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int scoreboard_activity = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int start_button = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int team_1_name_placeholder = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int team_2_name_placeholder = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int team_input_activity = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int title = 2131099652;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Scoreboard_Name = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int Scoreboard_Score = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
